version: 2
updates:

# Maintain dependencies for GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
  target-branch: "dependencies"
  assignees:
  - "yzhang-ampere"

# Maintain dependencies for python
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "monthly"
  target-branch: "dependencies"
  versioning-strategy: "increase-if-necessary"
  assignees:
  - "yzhang-ampere"
